codecov:
  token: b021643d-c806-4d00-9642-92a9d5774ccf
  require_ci_to_pass: true
comment:
  behavior: default
  layout: reach,diff,flags,tree
  require_changes: false
coverage:
  precision: 2
  range:
  - 0.0
  - 100.0
  round: down
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false