version: 2.1
orbs:
  node: circleci/node@5.1.0
  codecov: codecov/codecov@3.2.4
jobs:
  build-and-test:
    docker:
      - image: 'cimg/node:19.7.0'
    steps:
      - checkout
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get update -y
      - run:
          name: Update
          working_directory: /
          command: |
            sudo apt-get upgrade -y
      - run:
          name: Install Chrome headless dependencies
          working_directory: /
          command: |
            sudo apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
            libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libgbm-dev \
            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
            libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
            ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget --fix-missing 
      - run:
          name: Install npm
          working_directory: /
          command: |
            sudo apt-get install -y npm build-essential
      - run:
          name: Update npm
          working_directory: /
          command: |
            sudo npm install npm -g
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run coverage
          command: npm run coverage
          environment:
            JEST_JUNIT_OUTPUT_DIR: ~/project/reports/
      - run:
          name: Run tests
          command: npm run test
          environment:
            JEST_JUNIT_OUTPUT_DIR: ~/project/reports/
      - codecov/upload:
          flags: backend,unittest
      - store_artifacts:
          path: ~/project/dist
      - store_artifacts:
          path: ~/project/coverage
      - store_test_results:
          path: ~/project/reports/
   
resource_class: large
       
workflows:
  build-and-test:
    jobs:
      - build-and-test
