/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MenuItem,
} from './model/menu-item.model';
import {
  Context,
} from './model/context.model';

export namespace Components {
  interface PolarisAnalytics {}
  interface PolarisLoader {}
  interface PolarisMenu {
    'ctx'?: Context;
    'items': Array<MenuItem>|string;
  }
  interface PolarisWorkflow {
    'activity': string;
    'ctx': Context;
    'load': (process: any, next?: string, sessionId?: string) => Promise<void>;
    'parent': Context;
    'process': string|object;
    'sessionId': string;
    'setServices': (ctx: Context) => Promise<void>;
    'tag': string;
    'url': string;
    'value'?: any;
  }
}

declare global {


  interface HTMLPolarisAnalyticsElement extends Components.PolarisAnalytics, HTMLStencilElement {}
  var HTMLPolarisAnalyticsElement: {
    prototype: HTMLPolarisAnalyticsElement;
    new (): HTMLPolarisAnalyticsElement;
  };

  interface HTMLPolarisLoaderElement extends Components.PolarisLoader, HTMLStencilElement {}
  var HTMLPolarisLoaderElement: {
    prototype: HTMLPolarisLoaderElement;
    new (): HTMLPolarisLoaderElement;
  };

  interface HTMLPolarisMenuElement extends Components.PolarisMenu, HTMLStencilElement {}
  var HTMLPolarisMenuElement: {
    prototype: HTMLPolarisMenuElement;
    new (): HTMLPolarisMenuElement;
  };

  interface HTMLPolarisWorkflowElement extends Components.PolarisWorkflow, HTMLStencilElement {}
  var HTMLPolarisWorkflowElement: {
    prototype: HTMLPolarisWorkflowElement;
    new (): HTMLPolarisWorkflowElement;
  };
  interface HTMLElementTagNameMap {
    'polaris-analytics': HTMLPolarisAnalyticsElement;
    'polaris-loader': HTMLPolarisLoaderElement;
    'polaris-menu': HTMLPolarisMenuElement;
    'polaris-workflow': HTMLPolarisWorkflowElement;
  }
}

declare namespace LocalJSX {
  interface PolarisAnalytics {}
  interface PolarisLoader {}
  interface PolarisMenu {
    'ctx'?: Context;
    'items'?: Array<MenuItem>|string;
  }
  interface PolarisWorkflow {
    'activity'?: string;
    'ctx'?: Context;
    'onWfMessage'?: (event: CustomEvent<any>) => void;
    'parent'?: Context;
    'process'?: string|object;
    'sessionId'?: string;
    'tag'?: string;
    'url'?: string;
    'value'?: any;
  }

  interface IntrinsicElements {
    'polaris-analytics': PolarisAnalytics;
    'polaris-loader': PolarisLoader;
    'polaris-menu': PolarisMenu;
    'polaris-workflow': PolarisWorkflow;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'polaris-analytics': LocalJSX.PolarisAnalytics & JSXBase.HTMLAttributes<HTMLPolarisAnalyticsElement>;
      'polaris-loader': LocalJSX.PolarisLoader & JSXBase.HTMLAttributes<HTMLPolarisLoaderElement>;
      'polaris-menu': LocalJSX.PolarisMenu & JSXBase.HTMLAttributes<HTMLPolarisMenuElement>;
      'polaris-workflow': LocalJSX.PolarisWorkflow & JSXBase.HTMLAttributes<HTMLPolarisWorkflowElement>;
    }
  }
}


